## creating ml pipelines using dvc and yaml
## pipeline like : data_ingestion -> data_preprocessing ->feature_engineering -> model_training -> model_evaluation
## setting up a pipeline (without params)

stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/preprocessing.py
    deps:
    - data/raw
    - src/preprocessing.py
    outs:
    - data/interim
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/interim
    - src/feature_engineering.py
    outs:
    - data/processed
  model_training:
    cmd: python src/model_training.py
    deps:
    - data/processed
    - src/model_training.py
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model_evaluation.py
    metrics:
    - reports/metrics.json
  

  
